name: Update README.md 

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '18'
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name karthikmudunuri
        git config user.email karthikmudunuri999@gmail.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Updated README.md"
        git push origin main
